Repository Team-Apricot/apricot-application, pull requests merged in 2024-09, with the labels that each got.

#4 [Feat] 개인 이력 페이지 개발
  src/main/java/sandbox/apricot/resume/controller/ResumeController.java
  src/main/webapp/WEB-INF/views/developerIntroductionViews/heejung/heejung.jsp
  src/main/webapp/WEB-INF/views/developerIntroductionViews/heejung/projects.jsp
  src/main/webapp/WEB-INF/views/developerIntroductionViews/heejung/resume.jsp
  src/main/webapp/salguDevelopers/heejung/assets/css/heejung.css
  src/main/webapp/salguDevelopers/heejung/assets/img/How.png
  src/main/webapp/salguDevelopers/heejung/assets/img/checkmate.png
  src/main/webapp/salguDevelopers/heejung/assets/img/salgu.png
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#13 [Feat] 메인 페이지에 word Cloud 기능 추가
  src/main/webapp/WEB-INF/components/header.jsp
  src/main/webapp/WEB-INF/components/wordcloud.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/css/styles.css
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#17 [Feat] 로그인 화면 개발
  src/main/java/sandbox/apricot/member/controller/MemberController.java
  src/main/webapp/WEB-INF/components/header.jsp
  src/main/webapp/WEB-INF/components/login.jsp
  src/main/webapp/WEB-INF/components/wordcloud.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/css/member/login.css
  src/main/webapp/css/styles.css
  src/main/webapp/js/member/login.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#19 [Fix] 버그 수정
  src/main/webapp/WEB-INF/components/wordcloud.jsp
  src/main/webapp/css/styles.css
  src/main/webapp/js/member/login.js
Labels: 🐞 Bug

#21 [feat] 회원가입 화면 , 기능 구현
  src/main/java/sandbox/apricot/member/controller/MemberController.java
  src/main/webapp/WEB-INF/components/login.jsp
  src/main/webapp/WEB-INF/views/member/informationSignUp.jsp
  src/main/webapp/WEB-INF/views/member/signup.jsp
  src/main/webapp/css/member/login.css
  src/main/webapp/css/member/signup.css
  src/main/webapp/js/member/login.js
  src/main/webapp/js/member/signUp.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#23 [Feat] 마이페이지 화면 구현
  src/main/java/sandbox/apricot/member/controller/MemberController.java
  src/main/webapp/WEB-INF/components/footer.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/member/myPage.jsp
  src/main/webapp/css/member/mypage.css
  src/main/webapp/css/member/signup.css
  src/main/webapp/css/styles.css
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#24 [Feat] Spring Security 설정 사용자 기능 개발
  build.gradle
  src/main/java/sandbox/apricot/auth/config/MemberAuthFailureHandler.java
  src/main/java/sandbox/apricot/auth/config/MemberAuthSuccessHandler.java
  src/main/java/sandbox/apricot/auth/config/SecurityConfig.java
  src/main/java/sandbox/apricot/auth/controller/AuthController.java
  src/main/java/sandbox/apricot/auth/dto/MemberPrincipalDetails.java
  src/main/java/sandbox/apricot/auth/provider/MemberAuthenticatorProvider.java
  src/main/java/sandbox/apricot/auth/service/MemberPrincipalDetailService.java
  src/main/java/sandbox/apricot/common/entity/BaseTime.java
  src/main/java/sandbox/apricot/common/exception/ErrorCode.java
  src/main/java/sandbox/apricot/common/response/ApiResponse.java
  src/main/java/sandbox/apricot/member/controller/MemberController.java
  src/main/java/sandbox/apricot/member/controller/MemberRestController.java
  src/main/java/sandbox/apricot/member/dto/request/MemberLogin.java
  src/main/java/sandbox/apricot/member/dto/request/MemberRegister.java
  src/main/java/sandbox/apricot/member/dto/response/MemberInfo.java
  src/main/java/sandbox/apricot/member/entity/Member.java
  src/main/java/sandbox/apricot/member/entity/MemberRole.java
  src/main/java/sandbox/apricot/member/exception/MemberBusinessException.java
  src/main/java/sandbox/apricot/member/exception/MemberErrorCode.java
  src/main/java/sandbox/apricot/member/mapper/MemberMapper.java
  src/main/java/sandbox/apricot/member/service/MemberService.java
  src/main/java/sandbox/apricot/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/webapp/WEB-INF/components/header.jsp
  src/main/webapp/WEB-INF/components/login.jsp
  src/main/webapp/WEB-INF/views/member/register-interest.jsp
  src/main/webapp/WEB-INF/views/member/register.jsp
  src/main/webapp/css/member/login.css
  src/main/webapp/css/member/signup.css
  src/main/webapp/js/member/login.js
  src/main/webapp/js/member/signUp.js
Labels: 👷🏻 Build, 🕋 DB, ✨ Feat, 🎉 BE

#27 [Policy] 지역구별 혜택 출력 페이지 개발
  src/main/java/sandbox/apricot/WebConfig.java
  src/main/java/sandbox/apricot/auth/config/SecurityConfig.java
  src/main/java/sandbox/apricot/policy/controller/PolicyController.java
  src/main/java/sandbox/apricot/resume/controller/ResumeController.java
  src/main/resources/static/assets/img/Seoul_districts.svg
  src/main/resources/static/assets/img/logo.png
  src/main/webapp/WEB-INF/views/policy/area.jsp
  src/main/webapp/css/policy/area.css
  src/main/webapp/js/policy/area.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#30 [Feat] 회원 가입 및 관심사 등록 기능 개발
  src/main/java/sandbox/apricot/auth/service/MemberPrincipalDetailService.java
  src/main/java/sandbox/apricot/common/exception/GlobalExceptionHandler.java
  src/main/java/sandbox/apricot/common/response/ApiResponse.java
  src/main/java/sandbox/apricot/interest/dto/request/InterestRegister.java
  src/main/java/sandbox/apricot/interest/entity/Interest.java
  src/main/java/sandbox/apricot/interest/mapper/InterestMapper.java
  src/main/java/sandbox/apricot/interest/service/InterestService.java
  src/main/java/sandbox/apricot/interest/service/InterestServiceImpl.java
  src/main/java/sandbox/apricot/member/controller/MemberController.java
  src/main/java/sandbox/apricot/member/controller/MemberRestController.java
  src/main/java/sandbox/apricot/member/dto/request/MemberRegister.java
  src/main/java/sandbox/apricot/member/dto/request/MemberRegisterBasic.java
  src/main/java/sandbox/apricot/member/dto/request/MemberRegisterDetail.java
  src/main/java/sandbox/apricot/member/entity/Member.java
  src/main/java/sandbox/apricot/member/exception/MemberErrorCode.java
  src/main/java/sandbox/apricot/member/mapper/MemberMapper.java
  src/main/java/sandbox/apricot/member/service/MemberService.java
  src/main/java/sandbox/apricot/member/service/MemberServiceImpl.java
  src/main/java/sandbox/apricot/member/util/annotation/NickName.java
  src/main/java/sandbox/apricot/member/util/annotation/Password.java
  src/main/java/sandbox/apricot/member/util/exception/MemberBusinessException.java
  src/main/java/sandbox/apricot/member/util/exception/MemberErrorCode.java
  src/main/java/sandbox/apricot/member/util/validation/NickNameValidator.java
  src/main/java/sandbox/apricot/member/util/validation/PasswordValidator.java
  src/main/resources/application.yml
  src/main/resources/mapper/interest/InterestMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/webapp/WEB-INF/components/header.jsp
  src/main/webapp/WEB-INF/views/member/register-interest.jsp
  src/main/webapp/WEB-INF/views/member/register.jsp
  src/main/webapp/css/member/register.css
  src/main/webapp/js/member/register.js
  src/main/webapp/js/member/signUp.js
  src/test/java/sandbox/apricot/member/validation/NickNameValidatorTest.java
  src/test/java/sandbox/apricot/member/validation/PasswordValidatorTest.java
Labels: 🎉 BE

#34 [Feat] 개인 모달 창 구현
  src/main/webapp/WEB-INF/components/header.jsp
  src/main/webapp/assets/img/person.jpg
  src/main/webapp/css/styles.css
  src/main/webapp/js/index.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#37 [Feat] 회원 정보 조회 기능 구현
  src/main/java/sandbox/apricot/auth/dto/MemberPrincipalDetails.java
  src/main/java/sandbox/apricot/auth/provider/MemberAuthenticatorProvider.java
  src/main/java/sandbox/apricot/interest/dto/request/InterestRegister.java
  src/main/java/sandbox/apricot/interest/mapper/CategoryMapper.java
  src/main/java/sandbox/apricot/interest/mapper/InterestMapper.java
  src/main/java/sandbox/apricot/interest/service/InterestService.java
  src/main/java/sandbox/apricot/interest/service/InterestServiceImpl.java
  src/main/java/sandbox/apricot/interest/util/exception/InterestBusinessException.java
  src/main/java/sandbox/apricot/interest/util/exception/InterestErrorCode.java
  src/main/java/sandbox/apricot/interest/vo/Category.java
  src/main/java/sandbox/apricot/interest/vo/Interest.java
  src/main/java/sandbox/apricot/member/controller/MemberController.java
  src/main/java/sandbox/apricot/member/controller/MemberRestController.java
  src/main/java/sandbox/apricot/member/dto/request/MemberRegisterBasic.java
  src/main/java/sandbox/apricot/member/dto/request/MemberRegisterDetail.java
  src/main/java/sandbox/apricot/member/dto/response/MemberInfo.java
  src/main/java/sandbox/apricot/member/mapper/MemberMapper.java
  src/main/java/sandbox/apricot/member/service/MemberService.java
  src/main/java/sandbox/apricot/member/service/MemberServiceImpl.java
  src/main/java/sandbox/apricot/member/vo/Member.java
  src/main/java/sandbox/apricot/member/vo/MemberRole.java
  src/main/resources/application.yml
  src/main/resources/mapper/interest/CategoryMapper.xml
  src/main/resources/mapper/interest/InterestMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/webapp/WEB-INF/views/member/myPage.jsp
  src/test/java/sandbox/apricot/member/service/MemberServiceImplTest.java
Labels: ✨ Feat, ♻️ Refactor, 🧐 Tech. Review, 🎉 BE

#38 [Feat] 지도 버튼 클릭시 애니메이션 효과 구현
  src/main/resources/static/assets/img/Seoul_districts.svg
  src/main/webapp/WEB-INF/views/policy/area.jsp
  src/main/webapp/css/policy/area.css
  src/main/webapp/js/policy/area.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#42 [Feat] 지역구별 혜택 출력 페이지 개발 (2)
  src/main/java/sandbox/apricot/common/config/WebConfig.java
  src/main/java/sandbox/apricot/policy/controller/PolicyController.java
  src/main/resources/static/assets/img/logo.png
  src/main/webapp/WEB-INF/views/policy/area.jsp
  src/main/webapp/css/policy/area.css
  src/main/webapp/js/policy/area.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#40 [Feat] 혜택 상세 정보 조회 기능 개발
  src/main/java/sandbox/apricot/policy/controller/PolicyController.java
  src/main/java/sandbox/apricot/policy/dto/PolicyDetailDTO.java
  src/main/java/sandbox/apricot/policy/mapper/PolicyDetailMapper.java
  src/main/java/sandbox/apricot/policy/service/PolicyDetailService.java
  src/main/resources/mapper/policy/DetailMapper.xml
  src/main/webapp/WEB-INF/views/policy/detail.jsp
  src/main/webapp/assets/img/heart_icon2_0.8.png
  src/main/webapp/assets/img/heart_icon_0.8.png
  src/main/webapp/assets/img/mascot.png
  src/main/webapp/assets/img/share_icon2_0.8.png
  src/main/webapp/assets/img/share_icon_0.8.png
  src/main/webapp/css/policy/detail.css
  src/main/webapp/js/policy/detail.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat, 🎉 BE

#41 [Feat] 스크랩 기능 구현 , 스크랩 마이페이지 연결 , 마이페이지 정보수정 페이지 추가
  src/main/java/sandbox/apricot/member/controller/MemberController.java
  src/main/java/sandbox/apricot/scrap/controller/ScrapRestController.java
  src/main/java/sandbox/apricot/scrap/dto/request/ScrapRegister.java
  src/main/java/sandbox/apricot/scrap/dto/response/ScrapInfo.java
  src/main/java/sandbox/apricot/scrap/mapper/ScrapMapper.java
  src/main/java/sandbox/apricot/scrap/service/ScrapService.java
  src/main/java/sandbox/apricot/scrap/service/ScrapServiceImpl.java
  src/main/java/sandbox/apricot/scrap/vo/Scrap.java
  src/main/resources/application.yml
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/resources/mapper/scrap/ScrapMapper.xml
  src/main/webapp/WEB-INF/components/header.jsp
  src/main/webapp/WEB-INF/views/member/myPage.jsp
  src/main/webapp/WEB-INF/views/member/updateInfo.jsp
  src/main/webapp/WEB-INF/views/member/updatePassword.jsp
  src/main/webapp/assets/img/region/Dobonggu.png
  src/main/webapp/assets/img/region/Dongdaemungu.png
  src/main/webapp/assets/img/region/Dongjakgu.png
  src/main/webapp/assets/img/region/Eunpyeonggu.png
  src/main/webapp/assets/img/region/Gangbukgu.png
  src/main/webapp/assets/img/region/Gangdonggu.png
  src/main/webapp/assets/img/region/Gangnamgu.png
  src/main/webapp/assets/img/region/Gangseogu.png
  src/main/webapp/assets/img/region/Geumcheongu.png
  src/main/webapp/assets/img/region/Gurogu.png
  src/main/webapp/assets/img/region/Gwanakgu.png
  src/main/webapp/assets/img/region/Gwangjingu.png
  src/main/webapp/assets/img/region/Jongnogu.png
  src/main/webapp/assets/img/region/Junggu.png
  src/main/webapp/assets/img/region/Jungnanggu.png
  src/main/webapp/assets/img/region/Mapogu.png
  src/main/webapp/assets/img/region/Nowon gu.png
  src/main/webapp/assets/img/region/Seochogu.png
  src/main/webapp/assets/img/region/Seodaemungu.png
  src/main/webapp/assets/img/region/Seongbukgu.png
  src/main/webapp/assets/img/region/Seongdonggu.png
  src/main/webapp/assets/img/region/Songpagu.png
  src/main/webapp/assets/img/region/Yangcheongu.png
  src/main/webapp/assets/img/region/Yeongdeungpogu.png
  src/main/webapp/assets/img/region/Yongsangu.png
  src/main/webapp/css/member/mypage.css
  src/main/webapp/css/member/updateInfo.css
  src/main/webapp/css/member/updatePassword.css
  src/main/webapp/js/member/myPage.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat, 🎉 BE

#43 [Feat] 메인 페이지 및 회원 수정 기능 일부 개발 / JSP 리팩토링
  src/main/java/sandbox/apricot/auth/config/MemberAuthExceptionEntryPoint.java
  src/main/java/sandbox/apricot/auth/config/MemberAuthFailureHandler.java
  src/main/java/sandbox/apricot/auth/config/MemberAuthSuccessHandler.java
  src/main/java/sandbox/apricot/auth/config/SecurityConfig.java
  src/main/java/sandbox/apricot/auth/controller/AuthController.java
  src/main/java/sandbox/apricot/auth/provider/MemberAuthenticatorProvider.java
  src/main/java/sandbox/apricot/member/controller/MemberRestController.java
  src/main/java/sandbox/apricot/member/dto/request/UpdateAgeRange.java
  src/main/java/sandbox/apricot/member/dto/request/UpdateNickName.java
  src/main/java/sandbox/apricot/member/mapper/MemberMapper.java
  src/main/java/sandbox/apricot/member/service/MemberService.java
  src/main/java/sandbox/apricot/member/service/MemberServiceImpl.java
  src/main/java/sandbox/apricot/policy/controller/PolicyController.java
  src/main/resources/application.yml
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/webapp/WEB-INF/components/footer.jsp
  src/main/webapp/WEB-INF/components/header.jsp
  src/main/webapp/WEB-INF/components/login.jsp
  src/main/webapp/WEB-INF/components/salgu-intro.jsp
  src/main/webapp/WEB-INF/components/salgu-main.jsp
  src/main/webapp/WEB-INF/components/wordcloud.jsp
  src/main/webapp/WEB-INF/env/area-env.jsp
  src/main/webapp/WEB-INF/env/common-env.jsp
  src/main/webapp/WEB-INF/env/detail-env.jsp
  src/main/webapp/WEB-INF/env/index-intro-env.jsp
  src/main/webapp/WEB-INF/env/index-main-env.jsp
  src/main/webapp/WEB-INF/env/myPage-env.jsp
  src/main/webapp/WEB-INF/env/register-env.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/member/login.jsp
  src/main/webapp/WEB-INF/views/member/myPage.jsp
  src/main/webapp/WEB-INF/views/member/register-interest.jsp
  src/main/webapp/WEB-INF/views/member/register.jsp
  src/main/webapp/WEB-INF/views/member/updateInfo.jsp
  src/main/webapp/WEB-INF/views/member/updatePassword.jsp
  src/main/webapp/WEB-INF/views/policy/area.jsp
  src/main/webapp/WEB-INF/views/policy/detail.jsp
  src/main/webapp/assets/img/banner_2.png
  src/main/webapp/assets/img/banner_3.png
  src/main/webapp/assets/img/region/gangnam.png
  src/main/webapp/css/component/custom-carousel.css
  src/main/webapp/css/component/footer.css
  src/main/webapp/css/component/header.css
  src/main/webapp/css/component/intro-card.css
  src/main/webapp/css/component/search-bar.css
  src/main/webapp/css/member/login.css
  src/main/webapp/css/member/mypage.css
  src/main/webapp/css/member/updateInfo.css
  src/main/webapp/css/member/updatePassword.css
  src/main/webapp/css/styles.css
  src/main/webapp/css/views/index-main.css
  src/main/webapp/js/components/wordcloud.js
  src/main/webapp/js/index.js
  src/main/webapp/js/member/login.js
  src/main/webapp/js/member/myPage.js
  src/main/webapp/js/member/register.js
Labels: 🏷️ Comment, 🎨 Design, ✨ Feat, ♻️ Refactor, ⭐️ Style, 🐞 Bug, 🎉 BE

#46 [Feat] 정보 수정 기능 구현
  src/main/java/sandbox/apricot/member/controller/MemberController.java
  src/main/java/sandbox/apricot/member/controller/MemberRestController.java
  src/main/java/sandbox/apricot/member/dto/request/UpdateCareer.java
  src/main/java/sandbox/apricot/member/dto/request/UpdateGender.java
  src/main/java/sandbox/apricot/member/dto/request/UpdateMarriedStatus.java
  src/main/java/sandbox/apricot/member/dto/request/UpdateNumChild.java
  src/main/java/sandbox/apricot/member/mapper/MemberMapper.java
  src/main/java/sandbox/apricot/member/service/MemberService.java
  src/main/java/sandbox/apricot/member/service/MemberServiceImpl.java
  src/main/java/sandbox/apricot/scrap/dto/response/ScrapInfo.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/resources/mapper/scrap/ScrapMapper.xml
  src/main/webapp/WEB-INF/views/member/myPage.jsp
  src/main/webapp/WEB-INF/views/member/updateInfo.jsp
  src/main/webapp/css/member/updateInfo.css
  src/main/webapp/js/member/myPage.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat, 🎉 BE

#47 [Feat] 회원 수정(Update), 삭제(Delete) RestAPI 개발 및 지역구별 혜택 조회 기능 개발
  src/main/java/sandbox/apricot/auth/config/MemberAuthExceptionEntryPoint.java
  src/main/java/sandbox/apricot/auth/config/MemberAuthFailureHandler.java
  src/main/java/sandbox/apricot/auth/config/SecurityConfig.java
  src/main/java/sandbox/apricot/auth/provider/MemberAuthenticatorProvider.java
  src/main/java/sandbox/apricot/auth/service/MemberPrincipalDetailService.java
  src/main/java/sandbox/apricot/common/exception/GlobalExceptionHandler.java
  src/main/java/sandbox/apricot/interest/controller/InterestRestController.java
  src/main/java/sandbox/apricot/interest/mapper/InterestMapper.java
  src/main/java/sandbox/apricot/interest/service/InterestService.java
  src/main/java/sandbox/apricot/interest/service/InterestServiceImpl.java
  src/main/java/sandbox/apricot/member/controller/MemberRestController.java
  src/main/java/sandbox/apricot/member/dto/request/UpdatePassword.java
  src/main/java/sandbox/apricot/member/mapper/MemberMapper.java
  src/main/java/sandbox/apricot/member/service/MemberService.java
  src/main/java/sandbox/apricot/member/service/MemberServiceImpl.java
  src/main/java/sandbox/apricot/member/util/exception/MemberErrorCode.java
  src/main/java/sandbox/apricot/policy/controller/PolicyRestController.java
  src/main/java/sandbox/apricot/policy/dto/response/DistrictPolicy.java
  src/main/java/sandbox/apricot/policy/mapper/PolicyMapper.java
  src/main/java/sandbox/apricot/policy/service/PolicyService.java
  src/main/java/sandbox/apricot/policy/service/PolicyServiceImpl.java
  src/main/java/sandbox/apricot/scrap/controller/ScrapRestController.java
  src/main/resources/mapper/interest/InterestMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/resources/mapper/policy/PolicyMapper.xml
  src/main/webapp/js/components/wordcloud.js
  src/main/webapp/js/member/login.js
Labels: ✨ Feat, 🎉 BE

#50 [Feat] 상세페이지 TOC 기능 구현 및 디자인 적용
  src/main/java/sandbox/apricot/policy/dto/PolicyDetailDTO.java
  src/main/java/sandbox/apricot/policy/mapper/PolicyDetailMapper.java
  src/main/java/sandbox/apricot/policy/service/PolicyDetailService.java
  src/main/resources/mapper/policy/DetailMapper.xml
  src/main/webapp/WEB-INF/env/detail-env.jsp
  src/main/webapp/WEB-INF/views/policy/detail.jsp
  src/main/webapp/css/policy/detail.css
  src/main/webapp/css/policy/detail_sub.css
  src/main/webapp/js/policy/detail.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat, ♻️ Refactor

#57 [Feat] 워드 클라우드 지역구별 혜택 수 조회 기능 구현
  build.gradle
  src/main/java/sandbox/apricot/ApricotApplication.java
  src/main/java/sandbox/apricot/common/aop/CacheLogging.java
  src/main/java/sandbox/apricot/common/config/RedisConfig.java
  src/main/java/sandbox/apricot/common/exception/GlobalExceptionHandler.java
  src/main/java/sandbox/apricot/member/controller/MemberRestController.java
  src/main/java/sandbox/apricot/member/util/exception/MemberErrorCode.java
  src/main/java/sandbox/apricot/policy/service/PolicyServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
  src/main/webapp/WEB-INF/components/salgu-main.jsp
  src/main/webapp/assets/favicon.ico
  src/main/webapp/css/policy/area.css
  src/main/webapp/css/views/index-main.css
  src/main/webapp/js/components/wordcloud.js
Labels: 👷🏻 Build, ✨ Feat, 🎉 BE

#60 [Refactor] 전체적인 css 수정 및 반응형 적용
  src/main/webapp/WEB-INF/components/salgu-main.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/member/myPage.jsp
  src/main/webapp/WEB-INF/views/policy/detail.jsp
  src/main/webapp/WEB-INF/views/resume/heejung.jsp
  src/main/webapp/css/component/footer.css
  src/main/webapp/css/component/header.css
  src/main/webapp/css/member/mypage.css
  src/main/webapp/css/member/updateInfo.css
  src/main/webapp/css/policy/area.css
  src/main/webapp/css/policy/detail.css
  src/main/webapp/css/policy/detail_sub.css
  src/main/webapp/css/styles.css
  src/main/webapp/css/views/index-main.css
  src/main/webapp/js/components/wordcloud.js
Labels: 🎨 Design, 🎁 FE, ♻️ Refactor

#63 [Feat] 정책 검색 기능 구현
  src/main/java/sandbox/apricot/policy/controller/PolicyController.java
  src/main/java/sandbox/apricot/policy/dto/response/PolicyInfo.java
  src/main/java/sandbox/apricot/policy/mapper/PolicyMapper.java
  src/main/java/sandbox/apricot/policy/service/PolicyService.java
  src/main/java/sandbox/apricot/policy/service/PolicyServiceImpl.java
  src/main/java/sandbox/apricot/scrap/controller/ScrapRestController.java
  src/main/java/sandbox/apricot/scrap/service/ScrapService.java
  src/main/java/sandbox/apricot/scrap/service/ScrapServiceImpl.java
  src/main/resources/mapper/policy/PolicyMapper.xml
  src/main/resources/mapper/scrap/ScrapMapper.xml
  src/main/webapp/WEB-INF/components/salgu-main.jsp
  src/main/webapp/WEB-INF/env/policy-env.jsp
  src/main/webapp/WEB-INF/views/policy/policy.jsp
  src/main/webapp/css/component/search-bar.css
  src/main/webapp/css/policy/policy.css
  src/main/webapp/css/styles.css
  src/main/webapp/css/views/index-main.css
  src/main/webapp/js/index.js
  src/main/webapp/js/policy/policy.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat, 🐞 Bug, 🎉 BE

#62  [Recommendation] 지역구 추천 알고리즘 시스템 개발
  src/main/java/sandbox/apricot/auth/config/SecurityConfig.java
  src/main/java/sandbox/apricot/recommendation/controller/RecommendationController.java
  src/main/java/sandbox/apricot/recommendation/dto/response/DistrictScoreDTO.java
  src/main/java/sandbox/apricot/recommendation/dto/response/PolicyScoreDTO.java
  src/main/java/sandbox/apricot/recommendation/dto/response/ScrapGroupSimilarityDTO.java
  src/main/java/sandbox/apricot/recommendation/mapper/RecommendationMapper.java
  src/main/java/sandbox/apricot/recommendation/service/RecommendationService.java
  src/main/java/sandbox/apricot/recommendation/service/RecommendationServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/recommendation/Recommendation.xml
Labels: ✨ Feat, 🎉 BE

#65 [Feat] 혜택 삭제 기능 추가 및 여러가지 디자인 수정
  src/main/java/sandbox/apricot/policy/controller/PolicyController.java
  src/main/java/sandbox/apricot/scrap/controller/ScrapRestController.java
  src/main/java/sandbox/apricot/scrap/dto/request/ScrapDelete.java
  src/main/java/sandbox/apricot/scrap/dto/response/ScrapInfo.java
  src/main/java/sandbox/apricot/scrap/mapper/ScrapMapper.java
  src/main/java/sandbox/apricot/scrap/service/ScrapService.java
  src/main/java/sandbox/apricot/scrap/service/ScrapServiceImpl.java
  src/main/resources/mapper/scrap/ScrapMapper.xml
  src/main/webapp/WEB-INF/env/common-env.jsp
  src/main/webapp/WEB-INF/views/member/myPage.jsp
  src/main/webapp/WEB-INF/views/member/register-interest.jsp
  src/main/webapp/WEB-INF/views/member/updateInfo.jsp
  src/main/webapp/WEB-INF/views/policy/detail.jsp
  src/main/webapp/WEB-INF/views/policy/policy.jsp
  src/main/webapp/assets/img/age.png
  src/main/webapp/assets/img/baby.png
  src/main/webapp/assets/img/email.png
  src/main/webapp/assets/img/gender.png
  src/main/webapp/assets/img/job.png
  src/main/webapp/assets/img/marriage.png
  src/main/webapp/assets/img/person.png
  src/main/webapp/css/component/header.css
  src/main/webapp/css/member/login.css
  src/main/webapp/css/member/mypage.css
  src/main/webapp/css/member/register.css
  src/main/webapp/css/member/updateInfo.css
  src/main/webapp/css/member/updatePassword.css
  src/main/webapp/css/policy/area.css
  src/main/webapp/css/policy/detail.css
  src/main/webapp/css/policy/policy.css
  src/main/webapp/css/styles.css
  src/main/webapp/css/views/index-main.css
  src/main/webapp/js/member/myPage.js
  src/main/webapp/js/member/register.js
  src/main/webapp/js/policy/detail.js
  src/main/webapp/js/policy/policy.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat, 🔨 Fix, 🎉 BE

#69 [Feat] 정책 추천 기능 연동
  src/main/java/sandbox/apricot/policy/controller/PolicyController.java
  src/main/java/sandbox/apricot/recommendation/controller/RecommendationController.java
  src/main/resources/mapper/recommendation/Recommendation.xml
  src/main/webapp/WEB-INF/views/policy/detail.jsp
  src/main/webapp/css/policy/detail.css
Labels: 🎁 FE, ✨ Feat, 🎉 BE

#70 [Feat] 리뷰 기능 및 메인페이지 구조 변경
  src/main/webapp/WEB-INF/components/footer.jsp
  src/main/webapp/WEB-INF/components/salgu-main.jsp
  src/main/webapp/WEB-INF/views/member/updatePassword.jsp
  src/main/webapp/WEB-INF/views/policy/detail.jsp
  src/main/webapp/WEB-INF/views/policy/policy.jsp
  src/main/webapp/WEB-INF/views/policy/reviewModal.jsp
  src/main/webapp/css/component/custom-carousel.css
  src/main/webapp/css/component/footer.css
  src/main/webapp/css/component/header.css
  src/main/webapp/css/policy/detail.css
  src/main/webapp/css/policy/policy.css
  src/main/webapp/css/policy/reviewModal.css
  src/main/webapp/css/styles.css
  src/main/webapp/css/views/index-main.css
  src/main/webapp/js/member/myPage.js
  src/main/webapp/js/policy/detail.js
  src/main/webapp/js/policy/policy.js
Labels: 🎨 Design, 🎁 FE, ✨ Feat

#71 [Feat] 추천 뷰 개발
  src/main/java/sandbox/apricot/recommendation/controller/RecommendationController.java
  src/main/java/sandbox/apricot/recommendation/controller/RecommendationRestController.java
  src/main/java/sandbox/apricot/recommendation/dto/response/DistrictScoreDTO.java
  src/main/java/sandbox/apricot/recommendation/dto/response/RecommendationInfo.java
  src/main/java/sandbox/apricot/recommendation/dto/response/ScrapGroupSimilarityDTO.java
  src/main/java/sandbox/apricot/recommendation/service/RecommendationService.java
  src/main/java/sandbox/apricot/recommendation/service/RecommendationServiceImpl.java
  src/main/java/sandbox/apricot/recommendation/util/DataPreprocess.java
  src/main/webapp/WEB-INF/components/salgu-main.jsp
  src/main/webapp/WEB-INF/views/policy/recommendation.jsp
  src/main/webapp/css/policy/recommendation.css
  src/main/webapp/js/policy/recommendation.js
Labels: 🎁 FE

#73 [Fix] 정책 수 기반 환산 점수 오류 수정
  src/main/resources/mapper/recommendation/Recommendation.xml
Labels: 🚨 HotFix, 🐞 Bug

#74 [Feat] 관심사 수정 구현 및 css 수정
  src/main/webapp/WEB-INF/env/myPage-env.jsp
  src/main/webapp/WEB-INF/views/member/updateInfo.jsp
  src/main/webapp/WEB-INF/views/policy/recommendation.jsp
  src/main/webapp/assets/img/banner_2.png
  src/main/webapp/assets/img/bronzeMedal.png
  src/main/webapp/assets/img/goldMadal.png
  src/main/webapp/assets/img/interest.png
  src/main/webapp/assets/img/silverMedal.png
  src/main/webapp/css/member/updateInfo.css
  src/main/webapp/css/policy/recommendation.css
  src/main/webapp/css/policy/reviewModal.css
  src/main/webapp/js/member/myPage.js
  src/main/webapp/js/member/register.js
  src/main/webapp/js/member/update.js
  src/main/webapp/js/policy/recommendation.js
Labels: 🎨 Design

#68 [Feat] 이메일 인증 기능 개발
  build.gradle
  src/main/java/sandbox/apricot/auth/config/SecurityConfig.java
  src/main/java/sandbox/apricot/auth/service/MemberPrincipalDetailService.java
  src/main/java/sandbox/apricot/common/exception/GlobalExceptionHandler.java
  src/main/java/sandbox/apricot/common/response/ApiResponse.java
  src/main/java/sandbox/apricot/member/controller/EmailRestController.java
  src/main/java/sandbox/apricot/member/controller/PasswordResetController.java
  src/main/java/sandbox/apricot/member/service/EmailService.java
  src/main/java/sandbox/apricot/member/service/EmailServiceImpl.java
  src/main/java/sandbox/apricot/member/service/UserService.java
  src/main/java/sandbox/apricot/member/service/UserServiceImpl.java
  src/main/java/sandbox/apricot/member/util/exception/MemberErrorCode.java
  src/main/java/sandbox/apricot/member/vo/Member.java
  src/main/resources/application.yml
  src/main/webapp/WEB-INF/views/member/register.jsp
  src/main/webapp/css/member/register.css
  src/main/webapp/js/member/register.js
Labels: ✨ Feat, 🎉 BE

#76 [PolicyReview] 정책 리뷰 점수 반영
  src/main/java/sandbox/apricot/policy/mapper/PolicyMapper.java
  src/main/resources/mapper/policy/PolicyMapper.xml
  src/main/webapp/WEB-INF/views/policy/reviewModal.jsp
  src/main/webapp/js/policy/detail.js
Labels: 🕋 DB, 🎁 FE, 🎉 BE

#81 [Fix] 혜택 평점 기능 권한 설정
  src/main/webapp/WEB-INF/views/member/register-interest.jsp
  src/main/webapp/WEB-INF/views/member/updateInfo.jsp
  src/main/webapp/WEB-INF/views/policy/detail.jsp
  src/main/webapp/WEB-INF/views/policy/recommendation.jsp
Labels: 🔨 Fix
